### ISSUE TITLE
How do I change the radius or arc width of the slices?

### ISSUE THREAD

**Issue by kikidesignnet** [Arnaumes/radial-menu#1]
How do I change the radius or arc width of the circle? I wanted to use something similar to this image below.
![business-intelligence-1](https://user-images.githubusercontent.com/5368455/53265090-4f583880-36ab-11e9-8e9b-b9b18c3c6e7f.jpg)

**Comment by Arnaumes** [comment]
Hello, sorry for the late answer, I've not been very active on here until now.

You've probably moved on from this by now, but I'll answer anyways: 
In the css, under the .slice, modify the width and heigh options to make the elements bigger. You must then use the top and left options in .menunav to adjust the position of the central circle. However, as you must have realized by now, this menu was hardcoded for this size, which makes it difficult to adjust, and it won't be modular. I recommend you check out this pen instead, and go from there: https://codepen.io/juslwk/pen/xgbDB
I know your pain when it comes to making this shape in CSS, though.
